version: "3.3"

services:
  app:
    image: clip-go-image:latest
    networks:
      - web
      - default
    expose:
      - "8080"
    volumes:
      - /home/ec2-user/go/src/team-academy/res/:/res/
      - /home/ec2-user/go/src/team-academy/:/home/ec2-user/go/src/team-academy/
      - /home/ec2-user/go/src/team-academy/vendor/github.com/plicca/:/src/team-academy/vendor/github.com/plicca/
    labels:
      - traefik.docker.network=web
      - traefik.port=8080
      - traefik.backend=clip-go
      - traefik.frontend.rule=Host:clip.plicca.com
    environment:
      - GOPATH=/home/ec2-user/go/
networks:
  web:
    external: true
